import type { CSSProperties } from "react";

/** Co-located styles for IntentCard (incl. the Risk Areas accordion, AC-13). */
export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
  } satisfies CSSProperties,
  summary: {
    fontStyle: "italic",
    fontSize: 14,
    color: "var(--text-primary)",
    margin: "0 0 16px",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  columns: {
    display: "flex",
    gap: 24,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  col: {
    flex: 1,
    minWidth: 180,
  } satisfies CSSProperties,
  colHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginBottom: 10,
  } satisfies CSSProperties,
  scopeItem: {
    display: "flex",
    gap: 6,
    marginBottom: 6,
    alignItems: "flex-start",
  } satisfies CSSProperties,
  scopeText: {
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.4,
  } satisfies CSSProperties,
  emptyRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  muted: {
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  btn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  } satisfies CSSProperties,
  btnSmall: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: 5,
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-muted)",
    fontSize: 11,
    fontWeight: 600,
    cursor: "pointer",
  } satisfies CSSProperties,
  skeletonLine: {
    height: 14,
    borderRadius: 4,
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  spinning: {
    animation: "ddspin 1s linear infinite",
  } satisfies CSSProperties,

  // ---- Risk Areas accordion (AC-13) ----
  riskSection: {
    marginTop: 16,
    borderTop: "1px solid var(--border)",
    paddingTop: 14,
  } satisfies CSSProperties,
  riskSectionHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  } satisfies CSSProperties,
  riskLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--warn)",
  } satisfies CSSProperties,
  riskList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  riskItem: {
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "8px 10px",
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  riskItemHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: 0,
    border: "none",
    background: "transparent",
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
  riskItemTitle: {
    flex: 1,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    minWidth: 0,
  } satisfies CSSProperties,
  riskChevron: (expanded: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    transform: expanded ? "rotate(180deg)" : "none",
    transition: "transform .15s",
    flexShrink: 0,
  }),
  riskFileRefs: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
  } satisfies CSSProperties,
  riskFileRefBtn: {
    fontSize: 11,
    padding: "2px 6px",
    borderRadius: 4,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  riskExplanation: {
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    marginTop: 8,
    marginBottom: 0,
  } satisfies CSSProperties,
} as const;
