/**
 * Schema-drift guard for the multi-agent golden fixtures.
 *
 * These tests do NOT require Docker — they read committed JSON files from
 * __fixtures__/ and assert they parse cleanly against the Zod contracts.
 * The fixture files are generated by the fixture-generation tests in
 * service.it.test.ts (which require real Postgres).
 *
 * Run with: cd server && npm test
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { z } from 'zod';
import { MultiAgentRun, AgentEstimate } from '@devdigest/shared';

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), '__fixtures__');

describe('multi-agent fixture schema conformance', () => {
  it('multi-agent-run.fixture.json parses cleanly against MultiAgentRun', () => {
    const raw = JSON.parse(
      readFileSync(join(fixturesDir, 'multi-agent-run.fixture.json'), 'utf-8'),
    );
    expect(() => MultiAgentRun.parse(raw)).not.toThrow();
  });

  it('agent-estimates.fixture.json parses cleanly against z.array(AgentEstimate)', () => {
    const raw = JSON.parse(
      readFileSync(join(fixturesDir, 'agent-estimates.fixture.json'), 'utf-8'),
    );
    expect(() => z.array(AgentEstimate).parse(raw)).not.toThrow();
  });
});
